FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install kafka-python redis joblib pandas scikit-learn
COPY src/ ./src/
COPY models/ ./models/
CMD ["python", "-u", "src/kafka_consumer.py"]
