FROM python:3.11-slim

WORKDIR /app

# 1. Install dependencies from file
COPY requirements.txt .
# Added 'redis' and 'python-multipart' to the manual install list
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir fastapi uvicorn[standard] pydantic joblib pandas scikit-learn redis python-multipart

# 2. Copy the folders into the container
COPY src/ ./src/
COPY models/ ./models/

EXPOSE 8000

# 3. Start the app
CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
