# mainfest/fraud-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  namespace: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      containers:
      - name: fraud-api
        # Using the Artifact Registry image we just built
        image: us-central1-docker.pkg.dev/project-d1a95002-78b0-493b-b7e/fraud-repo/fraud-api:v10
        env:
        - name: MODEL_PATH
          value: "models/fraud_pipeline.joblib"
        - name: REDIS_HOST
          value: "redis-service" # This must match your Redis Service name
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: '500m'
            memory: '512Mi'
          limits:
            cpu: '2000m'
            memory: '2Gi'
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-api-svc
  namespace: fraud-detection
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  selector:
    app: fraud-api
  ports:
  - name: fraud-api-port
    port: 80
    targetPort: 8000
  type: ClusterIP # Changed to ClusterIP because you are using NEG/Gateway
